//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttractionsToGuidesTrips
    {
        public int id { get; set; }
        public int tripId { get; set; }
        public int attractionId { get; set; }
        public string distance { get; set; }
    
        public virtual TouristAttractions TouristAttractions { get; set; }
        public virtual TripsForJoining TripsForJoining { get; set; }
    }
}
