//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuidesForJoiningToSite
    {
        public int id { get; set; }
        public string guideName { get; set; }
        public string eMail { get; set; }
        public string phoneNumber { get; set; }
        public string languages { get; set; }
        public string workingDays { get; set; }
        public string password { get; set; }
        public string details { get; set; }
        public string profile { get; set; }
    }
}
