//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuideActivityDiary
    {
        public int id { get; set; }
        public int guideId { get; set; }
        public System.DateTime activityDate { get; set; }
    
        public virtual TourGuides TourGuides { get; set; }
    }
}
