//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Trips_DB : DbContext
    {
        public Trips_DB()
            : base("name=Trips_DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttractionsToCategories> AttractionsToCategories { get; set; }
        public virtual DbSet<AttractionsToGuidesTrips> AttractionsToGuidesTrips { get; set; }
        public virtual DbSet<AttractionsToUsersTrips> AttractionsToUsersTrips { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<GuideActivityDiary> GuideActivityDiary { get; set; }
        public virtual DbSet<GuidesForJoiningToSite> GuidesForJoiningToSite { get; set; }
        public virtual DbSet<ImagesUrl> ImagesUrl { get; set; }
        public virtual DbSet<TourGuides> TourGuides { get; set; }
        public virtual DbSet<TouristAttractions> TouristAttractions { get; set; }
        public virtual DbSet<TripsForJoining> TripsForJoining { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersTrips> UsersTrips { get; set; }
        public virtual DbSet<WaitingAttractions> WaitingAttractions { get; set; }
        public virtual DbSet<WaitingAttractionsImages> WaitingAttractionsImages { get; set; }
        public virtual DbSet<writtenDownUsers> writtenDownUsers { get; set; }
    }
}
