//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourGuides
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TourGuides()
        {
            this.GuideActivityDiary = new HashSet<GuideActivityDiary>();
            this.TripsForJoining = new HashSet<TripsForJoining>();
        }
    
        public int id { get; set; }
        public string guideName { get; set; }
        public string eMail { get; set; }
        public string phoneNumber { get; set; }
        public string languages { get; set; }
        public string workingDays { get; set; }
        public string password { get; set; }
        public string details { get; set; }
        public string profile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuideActivityDiary> GuideActivityDiary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripsForJoining> TripsForJoining { get; set; }
    }
}
