//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripsForJoining
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TripsForJoining()
        {
            this.AttractionsToGuidesTrips = new HashSet<AttractionsToGuidesTrips>();
        }
    
        public int id { get; set; }
        public int guideId { get; set; }
        public int maxOfTourists { get; set; }
        public int numOfSavedTourists { get; set; }
        public System.DateTime tripDate { get; set; }
        public string leavingTime { get; set; }
        public Nullable<int> price { get; set; }
        public string notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttractionsToGuidesTrips> AttractionsToGuidesTrips { get; set; }
        public virtual TourGuides TourGuides { get; set; }
    }
}
