//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTrips
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersTrips()
        {
            this.AttractionsToUsersTrips = new HashSet<AttractionsToUsersTrips>();
        }
    
        public int id { get; set; }
        public int userId { get; set; }
        public Nullable<int> guideId { get; set; }
        public string tripDate { get; set; }
        public bool isSentRequest { get; set; }
        public Nullable<bool> disagreeTrip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttractionsToUsersTrips> AttractionsToUsersTrips { get; set; }
    }
}
